// AUTO-GENERATED by scripts/generate_ts_types.py — DO NOT EDIT
// Source: packages/application/capability.py (Python 为 canonical schema 唯一事实源)
// Regenerate: python scripts/generate_ts_types.py

export const SCHEMA_VERSION = 1;

export interface CapabilityMeta {
  name: string;
  kind: "query" | "command" | "start_job";
  risk: "read_only" | "write" | "destructive";
  required_scope: "research:read" | "research:write" | "jobs:control" | "admin";
  supports_async: boolean;
  input_schema: Record<string, unknown>;
  output_schema: Record<string, unknown>;
  render_hint: string;
  surfaces: Record<string, string>;
}

export const CAPABILITIES: CapabilityMeta[] = [
  {
    "name": "search_papers",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "paper_list",
    "surfaces": {
      "terminal": "command",
      "mcp": "tool",
      "full_web": "GET /papers/search-multi"
    }
  },
  {
    "name": "get_paper",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "paper_card",
    "surfaces": {
      "terminal": "command",
      "local_ui": "PaperDetail",
      "full_web": "GET /papers/{id}",
      "mcp": "tool"
    }
  },
  {
    "name": "get_research_question",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "question_card",
    "surfaces": {
      "terminal": "command",
      "local_ui": "ClaimWorkspace",
      "full_web": "GET /research/questions/{id}",
      "mcp": "resource"
    }
  },
  {
    "name": "list_claims",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "claim_list",
    "surfaces": {
      "terminal": "command",
      "local_ui": "ClaimWorkspace",
      "full_web": "GET /research/questions/{id}/claims",
      "mcp": "resource"
    }
  },
  {
    "name": "get_claim_evidence",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "claim_evidence_card",
    "surfaces": {
      "terminal": "command",
      "local_ui": "ClaimEvidencePanel",
      "full_web": "GET /research/claims/{id}/evidence",
      "mcp": "resource"
    }
  },
  {
    "name": "diff_research_state",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "research_diff",
    "surfaces": {
      "terminal": "command",
      "local_ui": "ResearchDiff",
      "full_web": "GET /research/questions/{id}/diff",
      "mcp": "resource"
    }
  },
  {
    "name": "export_research_object",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "research_pack",
    "surfaces": {
      "terminal": "command",
      "local_ui": "ResearchPack",
      "full_web": "GET /research/questions/{id}/export",
      "mcp": "resource"
    }
  },
  {
    "name": "import_paper",
    "kind": "command",
    "risk": "write",
    "required_scope": "research:write",
    "supports_async": true,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "import_progress",
    "surfaces": {
      "terminal": "command",
      "full_web": "POST /ingest/arxiv",
      "mcp": "tool"
    }
  },
  {
    "name": "start_skim",
    "kind": "start_job",
    "risk": "write",
    "required_scope": "research:write",
    "supports_async": true,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "job_progress",
    "surfaces": {
      "terminal": "command",
      "full_web": "POST /pipelines/skim/{id}",
      "mcp": "tool"
    }
  },
  {
    "name": "start_deep_read",
    "kind": "start_job",
    "risk": "write",
    "required_scope": "research:write",
    "supports_async": true,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "job_progress",
    "surfaces": {
      "terminal": "command",
      "full_web": "POST /pipelines/deep/{id}",
      "mcp": "tool"
    }
  },
  {
    "name": "confirm_claim",
    "kind": "command",
    "risk": "write",
    "required_scope": "research:write",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "claim_card",
    "surfaces": {
      "terminal": "command",
      "local_ui": "ClaimWorkspace",
      "full_web": "POST（application command）"
    }
  },
  {
    "name": "cancel_job",
    "kind": "command",
    "risk": "write",
    "required_scope": "jobs:control",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "",
    "surfaces": {
      "terminal": "command",
      "local_ui": "JobMonitor",
      "full_web": "POST /jobs/{id}/cancel"
    }
  },
  {
    "name": "ask_knowledge_base",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "answer_card",
    "surfaces": {
      "terminal": "command",
      "mcp": "tool",
      "full_web": "POST /rag/ask"
    }
  },
  {
    "name": "get_daily_brief",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "brief_card",
    "surfaces": {
      "terminal": "command",
      "mcp": "tool",
      "full_web": "GET /brief"
    }
  },
  {
    "name": "get_similar_papers",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "paper_list",
    "surfaces": {
      "terminal": "command",
      "mcp": "tool",
      "full_web": "GET /papers/{id}/similar"
    }
  },
  {
    "name": "get_recommendations",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "paper_list",
    "surfaces": {
      "terminal": "command",
      "mcp": "tool",
      "full_web": "GET /papers/recommended"
    }
  },
  {
    "name": "list_topics",
    "kind": "query",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "topic_list",
    "surfaces": {
      "terminal": "command",
      "mcp": "tool",
      "full_web": "GET /topics"
    }
  },
  {
    "name": "start_daily_brief",
    "kind": "start_job",
    "risk": "write",
    "required_scope": "research:write",
    "supports_async": true,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "job_progress",
    "surfaces": {
      "terminal": "command",
      "full_web": "POST /brief/daily",
      "mcp": "tool"
    }
  },
  {
    "name": "start_topic_research",
    "kind": "start_job",
    "risk": "write",
    "required_scope": "research:write",
    "supports_async": true,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "job_progress",
    "surfaces": {
      "terminal": "command",
      "full_web": "POST /topics/{id}/fetch"
    }
  },
  {
    "name": "export_research_pack",
    "kind": "command",
    "risk": "read_only",
    "required_scope": "research:read",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "research_pack",
    "surfaces": {
      "terminal": "command",
      "local_ui": "ResearchPack",
      "full_web": "GET /research/questions/{id}/export"
    }
  },
  {
    "name": "manage_subscription",
    "kind": "command",
    "risk": "write",
    "required_scope": "research:write",
    "supports_async": false,
    "input_schema": {},
    "output_schema": {},
    "render_hint": "",
    "surfaces": {
      "terminal": "command",
      "full_web": "POST /topics"
    }
  }
];

export function getCapability(name: string): CapabilityMeta {
  const cap = CAPABILITIES.find(c => c.name === name);
  if (!cap) throw new Error(`capability ${name} not found`);
  return cap;
}


// ---------- canonical result view models ----------

export interface PaperView {
  id: string;
  title: string;
  arxiv_id: string;
  abstract: string;
  publication_date: string | null;
  read_status: "unread" | "skimmed" | "deep_read";
  pdf_path: string | null;
  has_embedding: boolean;
  favorited: boolean;
  categories: string[];
  keywords: string[];
  title_zh: string;
  abstract_zh: string;
  topics: string[];
  tags: string[];
}

export interface ClaimView {
  id: string;
  statement: string;
  statement_zh: string | null;
  origin: "author" | "papermind" | "user";
  status: "draft" | "pending_verification" | "confirmed" | "superseded" | "invalidated";
  certainty: "established" | "conditional" | "conflicted" | "insufficient_evidence" | "unknown";
  evidence_count: number;
  superseded_by_id: string | null;
  run_id: string | null;
  created_at: string | null;
}

export interface EvidenceView {
  id: string;
  claim_id: string;
  kind: "text_passage" | "figure" | "table" | "formula" | "numeric_result" | "dataset";
  stance: "supports" | "contradicts" | "context";
  locator: Record<string, unknown>;
  quote: string | null;
  experiment_conditions: Record<string, unknown> | null;
  extracted_by: "author" | "papermind" | "user";
  source_version: {
    id: string;
    version_label: number;
    external_version: string | null;
    content_hash: string;
    paper: { id: string; title: string; arxiv_id: string; doi: string | null };
  };
}

export interface JobView {
  id: string;
  kind: string;
  status: string;
  priority: number;
  progress: { current: number; total: number; message: string };
  created_at: string | null;
  started_at: string | null;
  finished_at: string | null;
  tasks: TaskView[];
}

export interface TaskView {
  id: string;
  seq: number;
  capability: string;
  status: "queued" | "leased" | "running" | "succeeded" | "failed" | "cancelled" | "dead_letter" | "manual_recovery";
  attempt_count: number;
  resource_class: string;
  last_error: string | null;
  external_ref: string | null;
}

export interface DiffItem {
  id: string;
  event: string;
  diff_kind: "added" | "confirmed" | "revised" | "invalidated" | "strengthened" | "weakened" | "conflict" | "superseded" | "retraction" | "context" | "relation" | "other";
  aggregate_id: string;
  actor: string;
  payload: Record<string, unknown>;
  occurred_at: string | null;
}

export interface ResearchObject {
  content_hash: string;
  generated_at: string;
  research_object: {
    ro_type: string;
    ro_version: number;
    question: Record<string, unknown>;
    claims: ClaimView[];
    evidence: EvidenceView[];
    relations: Record<string, unknown>[];
    source_versions: Record<string, unknown>[];
    provenance: Record<string, unknown>;
  };
}
