// Code generated by scripts/export_go_manifest.py from GO_APPLY_CAPABILITIES.
// DO NOT EDIT——运行脚本重新生成（CI 校验与源清单一致）。
package core

// GoApplyManifest：apply 已在 Go 实现的 A 档 capability（与 Python
// GO_APPLY_CAPABILITIES 同源生成）。
var GoApplyManifest = map[string]bool{
	"analyze_figures":            true,
	"build_daily_brief":          true,
	"deep_read_paper":            true,
	"download_source":            true,
	"embed_paper":                true,
	"extract_claims":             true,
	"generate_topic_wiki":        true,
	"import_references":          true,
	"import_selected":            true,
	"ingest_arxiv_query":         true,
	"skim_paper":                 true,
	"sync_citations_incremental": true,
	"sync_citations_paper":       true,
	"sync_citations_topic":       true,
	"translate_bilingual_pdf":    true,
	"upsert_paper":               true,
}
