"""initial schema

Revision ID: 4425bcca6b75
Revises:
Create Date: 2026-07-08 12:00:14.397780
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4425bcca6b75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_created_at'), 'agent_conversations', ['created_at'], unique=False)
    op.create_table('batch_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('paper_ids', sa.JSON(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_jobs_kind'), 'batch_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_batch_jobs_status'), 'batch_jobs', ['status'], unique=False)
    op.create_table('cs_categories',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('cs_feed_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cool_down_until', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cs_feed_subscriptions_category_code'), 'cs_feed_subscriptions', ['category_code'], unique=False)
    op.create_table('daily_report_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_deep_read', sa.Boolean(), nullable=False),
    sa.Column('deep_read_limit', sa.Integer(), nullable=False),
    sa.Column('send_email_report', sa.Boolean(), nullable=False),
    sa.Column('recipient_emails', sa.String(length=2048), nullable=False),
    sa.Column('cron_expression', sa.String(length=64), nullable=False),
    sa.Column('report_time_utc', sa.Integer(), nullable=False),
    sa.Column('include_paper_details', sa.Boolean(), nullable=False),
    sa.Column('include_graph_insights', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('smtp_server', sa.String(length=256), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('sender_email', sa.String(length=256), nullable=False),
    sa.Column('sender_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=True),
    sa.Column('model_skim', sa.String(length=128), nullable=False),
    sa.Column('model_deep', sa.String(length=128), nullable=False),
    sa.Column('model_vision', sa.String(length=128), nullable=True),
    sa.Column('model_embedding', sa.String(length=128), nullable=False),
    sa.Column('model_fallback', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('arxiv_id', sa.String(length=64), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('read_status', sa.Enum('unread', 'skimmed', 'deep_read', name='read_status'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('doi', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_papers_created_at'), 'papers', ['created_at'], unique=False)
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_favorited'), 'papers', ['favorited'], unique=False)
    op.create_index(op.f('ix_papers_read_status'), 'papers', ['read_status'], unique=False)
    op.create_index('ix_papers_read_status_created_at', 'papers', ['read_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_index(op.f('ix_papers_source_id'), 'papers', ['source_id'], unique=False)
    op.create_table('source_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('last_published_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('topic_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('query', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_results_per_run', sa.Integer(), nullable=False),
    sa.Column('retry_limit', sa.Integer(), nullable=False),
    sa.Column('schedule_frequency', sa.String(length=32), nullable=False),
    sa.Column('schedule_time_utc', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('ieee_daily_quota', sa.Integer(), nullable=False),
    sa.Column('ieee_api_key_override', sa.String(length=512), nullable=True),
    sa.Column('enable_date_filter', sa.Boolean(), nullable=False),
    sa.Column('date_filter_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_schemas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('research_topics', sa.JSON(), nullable=False),
    sa.Column('academic_level', sa.String(length=64), nullable=True),
    sa.Column('current_challenges', sa.JSON(), nullable=False),
    sa.Column('beliefs', sa.JSON(), nullable=False),
    sa.Column('knowledge_gaps', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_schemas_user_id'), 'user_schemas', ['user_id'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_conversation_id'), 'agent_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_table('agent_pending_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_pending_actions_conversation_id'), 'agent_pending_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_pending_actions_created_at'), 'agent_pending_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_pending_actions_paper_id'), 'agent_pending_actions', ['paper_id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('deep_dive_md', sa.Text(), nullable=True),
    sa.Column('key_insights', sa.JSON(), nullable=False),
    sa.Column('skim_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_paper_id'), 'analysis_reports', ['paper_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_paper_id', sa.String(length=36), nullable=False),
    sa.Column('target_paper_id', sa.String(length=36), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_paper_id', 'target_paper_id', name='uq_citation_edge')
    )
    op.create_index(op.f('ix_citations_source_paper_id'), 'citations', ['source_paper_id'], unique=False)
    op.create_index(op.f('ix_citations_target_paper_id'), 'citations', ['target_paper_id'], unique=False)
    op.create_table('collection_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('initial_import', 'manual_collect', 'auto_collect', 'agent_collect', 'subscription_ingest', 'reference_import', name='action_type'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('query', sa.String(length=1024), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_actions_action_type'), 'collection_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_collection_actions_topic_id'), 'collection_actions', ['topic_id'], unique=False)
    op.create_table('generated_contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_contents_content_type'), 'generated_contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_generated_contents_created_at'), 'generated_contents', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_contents_paper_id'), 'generated_contents', ['paper_id'], unique=False)
    op.create_table('ieee_api_quotas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('api_calls_used', sa.Integer(), nullable=False),
    sa.Column('api_calls_limit', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'date', name='uq_ieee_quota_daily')
    )
    op.create_index(op.f('ix_ieee_api_quotas_date'), 'ieee_api_quotas', ['date'], unique=False)
    op.create_index(op.f('ix_ieee_api_quotas_topic_id'), 'ieee_api_quotas', ['topic_id'], unique=False)
    op.create_table('image_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_index', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_analyses_paper_id'), 'image_analyses', ['paper_id'], unique=False)
    op.create_table('paper_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'tag_id', name='uq_paper_tag')
    )
    op.create_index(op.f('ix_paper_tags_paper_id'), 'paper_tags', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_tags_tag_id'), 'paper_tags', ['tag_id'], unique=False)
    op.create_table('paper_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'topic_id', name='uq_paper_topic')
    )
    op.create_index(op.f('ix_paper_topics_paper_id'), 'paper_topics', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_topics_topic_id'), 'paper_topics', ['topic_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('pipeline_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='pipeline_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_paper_id'), 'pipeline_runs', ['paper_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_name'), 'pipeline_runs', ['pipeline_name'], unique=False)
    op.create_table('prompt_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_digest', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost_usd', sa.Float(), nullable=True),
    sa.Column('output_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_traces_paper_id'), 'prompt_traces', ['paper_id'], unique=False)
    op.create_index(op.f('ix_prompt_traces_stage'), 'prompt_traces', ['stage'], unique=False)
    op.create_table('schema_paper_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_schema_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('interaction_type', sa.String(length=64), nullable=False),
    sa.Column('cognitive_delta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_schema_id'], ['user_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_paper_interactions_paper_id'), 'schema_paper_interactions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_schema_paper_interactions_user_schema_id'), 'schema_paper_interactions', ['user_schema_id'], unique=False)
    op.create_table('sensemaking_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('user_schema_id', sa.String(length=36), nullable=False),
    sa.Column('act1_comprehension', sa.JSON(), nullable=True),
    sa.Column('act2_collision', sa.JSON(), nullable=True),
    sa.Column('act3_reconstruction', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_schema_id'], ['user_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensemaking_sessions_paper_id'), 'sensemaking_sessions', ['paper_id'], unique=False)
    op.create_table('action_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['collection_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', 'paper_id', name='uq_action_paper')
    )
    op.create_index(op.f('ix_action_papers_action_id'), 'action_papers', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_papers_paper_id'), 'action_papers', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_papers_paper_id'), table_name='action_papers')
    op.drop_index(op.f('ix_action_papers_action_id'), table_name='action_papers')
    op.drop_table('action_papers')
    op.drop_index(op.f('ix_sensemaking_sessions_paper_id'), table_name='sensemaking_sessions')
    op.drop_table('sensemaking_sessions')
    op.drop_index(op.f('ix_schema_paper_interactions_user_schema_id'), table_name='schema_paper_interactions')
    op.drop_index(op.f('ix_schema_paper_interactions_paper_id'), table_name='schema_paper_interactions')
    op.drop_table('schema_paper_interactions')
    op.drop_index(op.f('ix_prompt_traces_stage'), table_name='prompt_traces')
    op.drop_index(op.f('ix_prompt_traces_paper_id'), table_name='prompt_traces')
    op.drop_table('prompt_traces')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_name'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_paper_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_paper_topics_topic_id'), table_name='paper_topics')
    op.drop_index(op.f('ix_paper_topics_paper_id'), table_name='paper_topics')
    op.drop_table('paper_topics')
    op.drop_index(op.f('ix_paper_tags_tag_id'), table_name='paper_tags')
    op.drop_index(op.f('ix_paper_tags_paper_id'), table_name='paper_tags')
    op.drop_table('paper_tags')
    op.drop_index(op.f('ix_image_analyses_paper_id'), table_name='image_analyses')
    op.drop_table('image_analyses')
    op.drop_index(op.f('ix_ieee_api_quotas_topic_id'), table_name='ieee_api_quotas')
    op.drop_index(op.f('ix_ieee_api_quotas_date'), table_name='ieee_api_quotas')
    op.drop_table('ieee_api_quotas')
    op.drop_index(op.f('ix_generated_contents_paper_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_created_at'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_content_type'), table_name='generated_contents')
    op.drop_table('generated_contents')
    op.drop_index(op.f('ix_collection_actions_topic_id'), table_name='collection_actions')
    op.drop_index(op.f('ix_collection_actions_action_type'), table_name='collection_actions')
    op.drop_table('collection_actions')
    op.drop_index(op.f('ix_citations_target_paper_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_source_paper_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_analysis_reports_paper_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_agent_pending_actions_paper_id'), table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_created_at'), table_name='agent_pending_actions')
    op.drop_index(op.f('ix_agent_pending_actions_conversation_id'), table_name='agent_pending_actions')
    op.drop_table('agent_pending_actions')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_conversation_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_user_schemas_user_id'), table_name='user_schemas')
    op.drop_table('user_schemas')
    op.drop_table('topic_subscriptions')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('source_checkpoints')
    op.drop_index(op.f('ix_papers_source_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index('ix_papers_read_status_created_at', table_name='papers')
    op.drop_index(op.f('ix_papers_read_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_favorited'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_index(op.f('ix_papers_created_at'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_table('llm_provider_configs')
    op.drop_table('email_configs')
    op.drop_table('daily_report_configs')
    op.drop_index(op.f('ix_cs_feed_subscriptions_category_code'), table_name='cs_feed_subscriptions')
    op.drop_table('cs_feed_subscriptions')
    op.drop_table('cs_categories')
    op.drop_index(op.f('ix_batch_jobs_status'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_kind'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    op.drop_index(op.f('ix_agent_conversations_created_at'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    # ### end Alembic commands ###
