"""从 Python registry 生成 Go 侧 manifest（单一事实源，消除双清单漂移）。

用法：python scripts/export_go_manifest.py  （CI/build 前运行；diff 非空则失败）
"""

from pathlib import Path

from packages.application.commands.jobs import GO_APPLY_CAPABILITIES

TEMPLATE = """// Code generated by scripts/export_go_manifest.py from GO_APPLY_CAPABILITIES.
// DO NOT EDIT——运行脚本重新生成（CI 校验与源清单一致）。
package core

// GoApplyManifest：apply 已在 Go 实现的 A 档 capability（与 Python
// GO_APPLY_CAPABILITIES 同源生成）。
var GoApplyManifest = map[string]bool{{
{entries}
}}
"""


def main() -> None:
    entries = "\n".join(f'\t"{name}": true,' for name in sorted(GO_APPLY_CAPABILITIES))
    out = Path(__file__).resolve().parents[1] / "core" / "capabilities_gen.go"
    out.write_text(TEMPLATE.format(entries=entries), encoding="utf-8")
    print(f"generated {out} ({len(GO_APPLY_CAPABILITIES)} capabilities)")


if __name__ == "__main__":
    main()
