"""F2：从 capability metadata 生成 TypeScript 类型定义（@papermind/presentation 种子）

构建期运行：python scripts/generate_ts_types.py
输出：packages/shared/presentation.ts（TS interface 定义）
Python 是 canonical schema 的唯一事实源（设计⑤ §2），TS 侧类型由此脚本生成。
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from packages.application.capability import export_capability_metadata

_TS_HEADER = """\
// AUTO-GENERATED by scripts/generate_ts_types.py — DO NOT EDIT
// Source: packages/application/capability.py (Python 为 canonical schema 唯一事实源)
// Regenerate: python scripts/generate_ts_types.py

export const SCHEMA_VERSION = {schema_version};

export interface CapabilityMeta {{
  name: string;
  kind: "query" | "command" | "start_job";
  risk: "read_only" | "write" | "destructive";
  required_scope: "research:read" | "research:write" | "jobs:control" | "admin";
  supports_async: boolean;
  input_schema: Record<string, unknown>;
  output_schema: Record<string, unknown>;
  render_hint: string;
  surfaces: Record<string, string>;
}}

export const CAPABILITIES: CapabilityMeta[] = {capabilities_json};

export function getCapability(name: string): CapabilityMeta {{
  const cap = CAPABILITIES.find(c => c.name === name);
  if (!cap) throw new Error(`capability ${{name}} not found`);
  return cap;
}}
"""

_TS_VIEW_MODELS = """

// ---------- canonical result view models ----------

export interface PaperView {
  id: string;
  title: string;
  arxiv_id: string;
  abstract: string;
  publication_date: string | null;
  read_status: "unread" | "skimmed" | "deep_read";
  pdf_path: string | null;
  has_embedding: boolean;
  favorited: boolean;
  categories: string[];
  keywords: string[];
  title_zh: string;
  abstract_zh: string;
  topics: string[];
  tags: string[];
}

export interface ClaimView {
  id: string;
  statement: string;
  statement_zh: string | null;
  origin: "author" | "papermind" | "user";
  status: "draft" | "pending_verification" | "confirmed" | "superseded" | "invalidated";
  certainty: "established" | "conditional" | "conflicted" | "insufficient_evidence" | "unknown";
  evidence_count: number;
  superseded_by_id: string | null;
  run_id: string | null;
  created_at: string | null;
}

export interface EvidenceView {
  id: string;
  claim_id: string;
  kind: "text_passage" | "figure" | "table" | "formula" | "numeric_result" | "dataset";
  stance: "supports" | "contradicts" | "context";
  locator: Record<string, unknown>;
  quote: string | null;
  experiment_conditions: Record<string, unknown> | null;
  extracted_by: "author" | "papermind" | "user";
  source_version: {
    id: string;
    version_label: number;
    external_version: string | null;
    content_hash: string;
    paper: { id: string; title: string; arxiv_id: string; doi: string | null };
  };
}

export interface JobView {
  id: string;
  kind: string;
  status: string;
  priority: number;
  progress: { current: number; total: number; message: string };
  created_at: string | null;
  started_at: string | null;
  finished_at: string | null;
  tasks: TaskView[];
}

export interface TaskView {
  id: string;
  seq: number;
  capability: string;
  status: "queued" | "leased" | "running" | "succeeded" | "failed" | "cancelled" | "dead_letter" | "manual_recovery";
  attempt_count: number;
  resource_class: string;
  last_error: string | null;
  external_ref: string | null;
}

export interface DiffItem {
  id: string;
  event: string;
  diff_kind: "added" | "confirmed" | "revised" | "invalidated" | "strengthened" | "weakened" | "conflict" | "superseded" | "retraction" | "context" | "relation" | "other";
  aggregate_id: string;
  actor: string;
  payload: Record<string, unknown>;
  occurred_at: string | null;
}

export interface ResearchObject {
  content_hash: string;
  generated_at: string;
  research_object: {
    ro_type: string;
    ro_version: number;
    question: Record<string, unknown>;
    claims: ClaimView[];
    evidence: EvidenceView[];
    relations: Record<string, unknown>[];
    source_versions: Record<string, unknown>[];
    provenance: Record<string, unknown>;
  };
}
"""


def generate_ts_types() -> str:
    metadata_json_str = export_capability_metadata()
    metadata = json.loads(metadata_json_str)
    capabilities_json = json.dumps(metadata["capabilities"], ensure_ascii=False, indent=2)

    ts = (
        _TS_HEADER.format(
            schema_version=metadata.get("schema_version", 1),
            capabilities_json=capabilities_json,
        )
        + _TS_VIEW_MODELS
    )
    return ts


def main() -> None:
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "packages", "shared")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "presentation.ts")
    ts = generate_ts_types()
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(ts)
    print(f"TS types exported to {out_path} ({len(ts)} bytes)")


if __name__ == "__main__":
    main()
